export const ADD_INITIAL_PASSAGE = 'ADD_INITIAL_PASSAGE';
export const GO_STAGE_TWO = 'GO_STAGE_TWO';
export const CHANGE_PASSAGE = 'CHANGE_PASSAGE';
export const GO_BACK_INITIAL = 'GO_BACK_INITIAL';
export const GO_BACK_CHANGE = 'GO_BACK_CHANGE';
export const COMPARE_PASSAGES = 'COMPARE_PASSAGES';